import React from 'react';
import { User, Activity, AlertCircle } from 'lucide-react';
import { getClinicalFacts } from '../lib/clinical_facts';

const FEATURE_LABEL_MAP = {
  Age: 'Age',
  Sex: 'Biological Sex',
  RestingBP: 'Resting Blood Pressure',
  Cholesterol: 'Serum Cholesterol',
  FastingBS: 'Fasting Blood Sugar',
  MaxHR: 'Maximum Heart Rate',
  ExerciseAngina: 'Exercise-Induced Angina',
  Oldpeak: 'ST Depression (Oldpeak)',
  ChestPainType_ASY: 'Chest Pain (Asymptomatic)',
  ChestPainType_ATA: 'Chest Pain (Atypical Angina)',
  ChestPainType_NAP: 'Chest Pain (Non-Anginal)',
  ChestPainType_TA: 'Chest Pain (Typical Angina)',
  RestingECG_LVH: 'Resting ECG (Hypertrophy)',
  RestingECG_Normal: 'Resting ECG (Normal)',
  RestingECG_ST: 'Resting ECG (ST-T wave)',
  ST_Slope_Down: 'ST Slope (Downsloping)',
  ST_Slope_Flat: 'ST Slope (Flat)',
  ST_Slope_Up: 'ST Slope (Upsloping)',
};

function AssessmentReportTemplate({ result, formData, generatedAt }) {
  const probability = result.heart_disease_probability ?? 0;
  const features = result.top_influencing_features ?? [];
  const maxAbsShap = Math.max(...features.map((feature) => Math.abs(feature.shap_value)), 0.001);

  return (
    <div
      style={{
        width: '720px',
        minHeight: '960px',
        padding: '32px',
        paddingTop: 0,
        boxSizing: 'border-box',
        fontFamily: 'system-ui, sans-serif',
        backgroundColor: '#ffffff',
        color: '#18181b',
      }}
    >
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'flex-start',
          borderBottom: '1px solid #e4e4e7',
          paddingBottom: '0px',
        }}
      >
        <div>
          <h1
            style={{
              fontSize: '1.875rem',
              lineHeight: '2.25rem',
              fontWeight: 700,
              letterSpacing: '-0.025em',
              color: '#0f766e',
              margin: 0,
            }}
          >
            Cardiovascular Health Assessment
          </h1>
          <p style={{ color: '#71717a', marginTop: '4px' }}>
            Generated by OrsusHealth Machine Learning Analysis Engine
          </p>
        </div>
        <div style={{ textAlign: 'right' }}>
          <p
            style={{
              fontSize: '0.875rem',
              lineHeight: '1.25rem',
              fontWeight: 600,
              color: '#27272a',
            }}
          >
            {generatedAt}
          </p>
          <p style={{ fontSize: '0.75rem', lineHeight: '1rem', color: '#a1a1aa' }}>
            Confidential / Patient Copy
          </p>
        </div>
      </div>

      <div style={{ display: 'flex', gap: '32px', marginBottom: '5px' }}>
        <div
          style={{
            flex: 1,
            backgroundColor: '#ffffff',
            border: '1px solid #e4e4e7',
            borderRadius: '12px',
            boxShadow: '0 1px 2px 0 rgba(0,0,0,0.05)',
            padding: '14px',
          }}
        >
          <h2
            style={{
              marginTop: 0,
              fontSize: '1.125rem',
              lineHeight: '1.75rem',
              fontWeight: 700,
              borderBottom: '1px solid #f4f4f5',
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
            }}
          >
            <User style={{ width: '20px', height: '20px', color: '#0d9488', position: 'relative', top: '-1px' }} /> Patient
            Profile
          </h2>
          <ul
            style={{
              display: 'flex',
              flexDirection: 'column',
              gap: '5px',
              paddingRight: '5px',
              paddingLeft: '5px',
              marginTop: '10px',
              fontSize: '0.875rem',
              lineHeight: '1.25rem',
              listStyle: 'none',
              margin: '10px 0 0 0',
            }}
          >
            <li style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ color: '#71717a', fontWeight: 500 }}>Full Name</span>
              <span style={{ fontWeight: 600, color: '#18181b', textAlign: 'right' }}>
                {formData.FullName || 'Not Provided'}
              </span>
            </li>
            <li style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ color: '#71717a', fontWeight: 500 }}>Age</span>
              <span style={{ fontWeight: 600, color: '#18181b', textAlign: 'right' }}>{formData.Age} Years</span>
            </li>
            <li style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ color: '#71717a', fontWeight: 500 }}>Biological Sex</span>
              <span style={{ fontWeight: 600, color: '#18181b', textAlign: 'right' }}>
                {formData.Sex === 'M' ? 'Male' : 'Female'}
              </span>
            </li>
            <li style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ color: '#71717a', fontWeight: 500 }}>Resting Blood Pressure</span>
              <span style={{ fontWeight: 600, color: '#18181b', textAlign: 'right' }}>
                {formData.RestingBP || 'N/A'} mmHg
              </span>
            </li>
            <li style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ color: '#71717a', fontWeight: 500 }}>Cholesterol</span>
              <span style={{ fontWeight: 600, color: '#18181b', textAlign: 'right' }}>
                {formData.Cholesterol || 'N/A'} mg/dl
              </span>
            </li>
          </ul>
        </div>

        <div
          style={{
            flex: 1,
            backgroundColor: '#fafafa',
            borderRadius: '12px',
            padding: '14px',
            border: '1px solid #f4f4f5',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <h2
            style={{
              fontSize: '0.875rem',
              lineHeight: '1.25rem',
              fontWeight: 600,
              color: '#71717a',
              textTransform: 'uppercase',
              letterSpacing: '0.1em',
              marginBottom: '16px',
            }}
          >
            Risk Probability Score
          </h2>
          <div style={{ fontSize: '3.15rem', lineHeight: 1, fontWeight: 700, color: probability > 50 ? '#e11d48' : '#0d9488' }}>
            {probability.toFixed(1)}%
          </div>
          <p style={{ fontSize: '0.75rem', lineHeight: '1rem', color: '#a1a1aa', marginTop: '12px', textAlign: 'center' }}>
            This indicates the estimated likelihood of cardiovascular complications based on your clinical profile.
          </p>
        </div>
      </div>

      <div>
        <h2
          style={{
            fontSize: '1.25rem',
            lineHeight: '1.75rem',
            fontWeight: 700,
            color: '#27272a',
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            borderBottom: '1px solid #e4e4e7',
            marginBottom: '5px',
          }}
        >
          <Activity style={{ width: '20px', height: '20px', color: '#0d9488' }} /> Key Influencing Factors
        </h2>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
          {features.map((item, idx) => {
            const isPositive = item.shap_value > 0;
            const barWidth = `${(Math.abs(item.shap_value) / maxAbsShap) * 100}%`;
            const displayLabel = FEATURE_LABEL_MAP[item.feature] || item.feature;

            return (
              <div
                key={idx}
                style={{
                  display: 'flex',
                  flexDirection: 'column',
                  gap: '6px',
                  padding: '8px',
                  backgroundColor: '#fafafa',
                  borderRadius: '8px',
                  border: '1px solid rgba(0,0,0,0.05)',
                }}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <span style={{ fontWeight: 600, color: '#27272a', fontSize: '0.875rem', lineHeight: '1.25rem' }}>
                    {displayLabel}
                  </span>
                  <span
                    style={{
                      fontSize: '10px',
                      fontWeight: 700,
                      padding: '2px 8px',
                      borderRadius: '9999px',
                      textTransform: 'uppercase',
                      letterSpacing: '0.05em',
                      backgroundColor: isPositive ? '#ffe4e6' : '#ccfbf1',
                      color: isPositive ? '#be123c' : '#0f766e',
                    }}
                  >
                    {isPositive ? 'Increases Risk' : 'Decreases Risk'}
                  </span>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <div
                    style={{
                      flex: 1,
                      height: '12px',
                      backgroundColor: '#e4e4e7',
                      borderRadius: '9999px',
                      overflow: 'hidden',
                      display: 'flex',
                      boxShadow: 'inset 0 2px 4px 0 rgba(0,0,0,0.05)',
                    }}
                  >
                    {isPositive ? <div style={{ width: '50%' }} /> : null}
                    {!isPositive ? (
                      <div style={{ width: '50%', display: 'flex', justifyContent: 'flex-end' }}>
                        <div style={{ height: '100%', backgroundColor: '#14b8a6', borderRadius: '9999px 0 0 9999px', width: barWidth }} />
                      </div>
                    ) : (
                      <div style={{ width: '50%', display: 'flex', justifyContent: 'flex-start' }}>
                        <div style={{ height: '100%', backgroundColor: '#f43f5e', borderRadius: '0 9999px 9999px 0', width: barWidth }} />
                      </div>
                    )}
                    {!isPositive ? <div style={{ width: '50%' }} /> : null}
                  </div>
                  <span
                    style={{
                      fontSize: '0.75rem',
                      lineHeight: '1rem',
                      color: '#71717a',
                      fontWeight: 700,
                      fontVariantNumeric: 'tabular-nums',
                      width: '48px',
                      textAlign: 'right',
                    }}
                  >
                    {isPositive ? '+' : ''}
                    {item.shap_value.toFixed(2)}
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      <div style={{ marginTop: '10px' }}>
        <h2
          style={{
            fontSize: '1.25rem',
            lineHeight: '1.75rem',
            fontWeight: 700,
            color: '#27272a',
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            borderBottom: '1px solid #e4e4e7',
            marginBottom: '5px',
          }}
        >
          <AlertCircle style={{ width: '20px', height: '20px', color: '#0d9488' }} /> Clinical Recommendations
        </h2>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
          {features.map((item, idx) => {
            const isPositive = item.shap_value > 0;
            const clinicalData = getClinicalFacts(item.feature, isPositive);
            const displayLabel = FEATURE_LABEL_MAP[item.feature] || item.feature;

            return (
              <div
                key={idx}
                style={{
                  breakInside: 'avoid',
                  backgroundColor: '#ffffff',
                  borderRadius: '12px',
                  border: '1px solid #e4e4e7',
                  padding: '0px 14px',
                }}
              >
                <h3
                  style={{
                    fontWeight: 700,
                    fontSize: '1.125rem',
                    lineHeight: '1.75rem',
                    color: '#18181b',
                    display: 'flex',
                    alignItems: 'center',
                    marginTop: "10px",
                    marginBottom: "0px",
                  }}
                >
                  {idx + 1}. {displayLabel} Analysis
                </h3>
                <p style={{ fontSize: '0.875rem', lineHeight: '1.625', color: '#3f3f46', marginTop: "10px", marginBottom: "5px" }}>{clinicalData.fact}</p>
                <div
                  style={{
                    backgroundColor: '#f0fdfa',
                    borderLeft: '4px solid #14b8a6',
                    padding: '8px',
                    borderRadius: '0 6px 6px 0',
                    marginBottom: '6px',
                  }}
                >
                  <p
                    style={{
                      fontSize: '0.875rem',
                      lineHeight: '1.25rem',
                      color: '#134e4a',
                      display: 'flex',
                      gap: '5px',
                      margin: 0,
                    }}
                  >
                    <strong style={{ whiteSpace: 'nowrap' }}>Recommendation:</strong> <span>{clinicalData.suggestion}</span>
                  </p>
                </div>
                <p style={{ fontSize: '0.75rem', lineHeight: '1rem', color: '#a1a1aa', fontStyle: 'italic', marginTop: 0 }}>
                  Source: {clinicalData.citation}
                </p>
              </div>
            );
          })}
        </div>
      </div>

      <div style={{ marginBottom: '5px', breakInside: 'avoid' }}>
        <h2
          style={{
            fontSize: '1.125rem',
            lineHeight: '1.75rem',
            fontWeight: 700,
            color: '#27272a',
            marginBottom: '3px',
            borderBottom: '1px solid #e4e4e7',
          }}
        >
          References
        </h2>
        <div style={{ display: 'flex', flexDirection: 'column' }}>
          {(() => {
            const citedSources = features.reduce((sources, item) => {
              const citationText = getClinicalFacts(item.feature, item.shap_value > 0).citation;

              let org = 'American Heart Association';
              let url = 'https://www.heart.org/';

              if (citationText.includes('ACC') || citationText.includes('College of Cardiology')) {
                org = 'American College of Cardiology';
                url = 'https://www.acc.org/';
              } else if (citationText.includes('ADA')) {
                org = 'American Diabetes Association';
                url = 'https://diabetes.org/';
              } else if (citationText.includes('CCS') || citationText.includes('Canadian Cardiovascular')) {
                org = 'Canadian Cardiovascular Society';
                url = 'https://ccs.ca/';
              } else if (citationText.includes('Diabetes Canada')) {
                org = 'Diabetes Canada';
                url = 'https://www.diabetes.ca/';
              }

              const existingSource = sources.find((source) => source.url === url);
              if (!existingSource) {
                sources.push({ org, url, primaryCitation: citationText });
              }

              return sources;
            }, []);

            return citedSources.map((source, idx) => (
              <p key={idx} style={{ fontSize: '0.75rem', lineHeight: '1rem', color: '#52525b', overflowWrap: 'break-word', marginTop: 0}}>
                {source.org}. (n.d.). <em>{source.primaryCitation}</em>. Retrieved {generatedAt}, from{' '}
                <a href={source.url} target="_blank" rel="noopener noreferrer" style={{ color: '#0d9488', textDecoration: 'none' }}>
                  {source.url}
                </a>
              </p>
            ));
          })()}
        </div>
      </div>

      <div
        style={{
          textAlign: 'left',
          fontSize: '11px',
          letterSpacing: '-0.025em',
          whiteSpace: 'nowrap',
          color: '#a1a1aa',
          paddingTop: '1px',
          borderTop: '1px solid #e4e4e7',
        }}
      >
        This report was computationally generated by OrsusHealth AI and is for informational purposes only. It is not a
        substitute for professional medical advice.
      </div>
    </div>
  );
}

export default AssessmentReportTemplate;
